"""Runtime configuration for Cryptoriale."""

OLLAMA_HOST = "http://localhost:11434"
OLLAMA_MODEL = "llama3"
PARSER_TEMPERATURE = 0.0
NARRATOR_TEMPERATURE = 0.4
AUTO_PULL_ON_STARTUP = True
OLLAMA_STARTUP_TIMEOUT_SEC = 90
